### PR TITLE
for run dfttk on multiple computer etc

### PR DESCRIPTION
**Pull request by yiwang62**
for run dfttk on multiple computer, database hard issues, and Poisson ratio based on Cij, Elastic constant calculation etc. After this review, we will new release

### CODE REVIEW

**Comment by bocklund** [comment]
@yiwang62 can you fix the conflicts before we review?

**Comment by bocklund** [comment]
Thanks! You should also consider creating new branches from DFTTK master as you work on new things. And make sure that your fork of DFTTK uses this repository with the clean history, rather than the old (now archived) repository with the messy history.

**Comment by yiwang62** [comment]
> Thanks! You should also consider creating new branches from DFTTK master as you work on new things. And make sure that your fork of DFTTK uses this repository with the clean history, rather than the old (now archived) repository with the messy history.

Thanks! once this one is merged into the master, I will use master to branch

**Comment by yiwang62** [comment]
> @yiwang62 can you fix the conflicts before we review?
I fixed all conflicts

**Review by ShuangLin212 — APPROVED** [review]

**Review by RushiGong — APPROVED** [review]

**Review by ShuangLin212 — APPROVED** [review]

**Pull request closed without merging**
